# Use the official Node.js image as the base
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the container
COPY package*.json /usr/src/app

# Install the dependencies
RUN npm install

# Copy the rest of the backend code to the container
COPY . .

# Expose the port on which the backend will run
EXPOSE 8080

# Start the backend server
CMD ["node", "app.js"]
